### ISSUE TITLE
Question about kernelbase.lib

### ISSUE THREAD

**Issue by Thomas1995** [ionescu007/HookingNirvana#1]
Hello, I didn't know how else to get in touch regarding one question I have about MinWin Hook.

As far I have understood, to avoid being the subject of redirection, you have to import the api functions directly from the .lib. In the test folder, at AdditionalDependencies, there is "c:\recon\kernelbase.lib", which I need in order to build the code.

Any guidance or advice on this? How can I get that .lib?

Thank you for your attention!

**Comment by ionescu007** [comment]
From the Windows SDK.

Best regards,
Alex Ionescu

**Comment by evandrix** [comment]
https://github.com/MakiseKurisu/WindowsRTLib/blob/master/Lib/KernelBase.lib

**Comment by evandrix** [comment]
https://github.com/peterdn/dll2lib
